### ISSUE TITLE
core microservice proof-of-concept

### ISSUE THREAD

**Issue by mmskv** [mekstack/nataas#10]
# NATaaS Core POC

This service allows clients to
1. Issue a subdomain on behalf of their project (example: user `abexample` can issue a `kot.mekstack.ru` subdomain for project `100`) 
2. Set up a route for one of their subdomains (example: route `kot.mekstack.ru` to `172.18.218.59`)
3. View routes of all other projects
4. Send a notification of route addition to envoy-manager

- Routes should be stored in sqlite for POC, in Redis for actual implementation 

# Todo

- [ ] Simple js/svelte/any-hyped-up-framework frontend
- [x] **Design gRPC protos for the core service that will interact with envoy-manager microservice #8** 
- [x] Write an application that acts as a gRPC server and performs the tasks mentioned above
